### ISSUE TITLE
PC-9821Ra20 memory size detected improperly, throws errors past RAM limit. 

### ISSUE THREAD

**Issue by Pawlicker** [mcDomDom/memtest_98#1]
When running memtest on my PC-9821Ra20 (i440fx chipset), errors are generated as the system tries to test past the RAM limit and returns 00000000 resulting in the window and test filling up with errors. While the tool detects 79MB, it tries to test past that into 80MB. The 16mb memory hole option is on as it is by default. 
![IMG_20230304_142522](https://user-images.githubusercontent.com/92184373/222925478-35a2ee48-c290-4b7b-b8b9-8bb123d3e500.jpg)

**Comment by mcDomDom** [comment]
Thanks for the report. This is a known issue where using 16MB system space the valid memory range check returns a range larger than max memory as in the first image. Please test by disconnecting 16MB system space like the second image.
![IMG20230305185755](https://user-images.githubusercontent.com/126031341/222954017-cbde3fcd-b3a1-4afd-bef8-ebd983e78ca7.jpg)
![IMG20230305184731](https://user-images.githubusercontent.com/126031341/222954023-e6c9a595-4d25-425b-a802-1241dcaf95a8.jpg)

**Comment by Pawlicker** [comment]
Thanks, that worked on this model and the test runs fine.  I can confirm it works just fine on the Ra20 with this setting off.

**Comment by scramble45** [comment]
Can confirm this also works on a PC-9821 ra43 as well.

**Comment by mcDomDom** [comment]
Thank you for the report
